### ISSUE TITLE
Add expansion symbols for box sets, promos, modern masters, etc.

### ISSUE THREAD

**Issue by jninnes** [jninnes/mtgicons#10]
Add all missing expansion symbols
- box sets
- modern masters
- promos

**Comment by jninnes** [comment]
Done modern masters, masters edition 1-4, starter

**Comment by davidsoderberg** [comment]
What are the status for event decks?

**Comment by jninnes** [comment]
Most of this icons are already included in the font files in https://github.com/jninnes/mtgicons/blob/master/src/fonts/mtgicons.svg

The CSS needs to be cleaned up and moved from https://github.com/jninnes/mtgicons/blob/master/src/icomoon/style.css to https://github.com/jninnes/mtgicons/blob/master/src/expansions.less

eg 

    .H0201-PremiumDeckSeriesFireLightning-Common .path1:before {
        content: "\e79f";
        color: rgb(255, 255, 255);
    }
    .H0201-PremiumDeckSeriesFireLightning-Common .path2:before {
        content: "\e7a0";
        margin-left: -0.732421875em;
        color: rgb(0, 0, 0);
    }

becomes something like

    .pds-fire-lightning:before {
         content: "\e79f";
         color: rgb(255, 255, 255);
    }
    .pds-fire-lightning:after {
        content: "\e7a0";
        margin-left: -0.732421875em;
        color: rgb(0, 0, 0);
    }

Then these icons need to be added to the demo at https://github.com/jninnes/mtgicons/blob/master/demo/demo.html

**Comment by jninnes** [comment]
Let me know what icons you need and I can priorities those ones, or make the changes yourself and send me a pull request.

**Comment by davidsoderberg** [comment]
I need all the icons :smile: 
Have you added this icon:http://archive.wizards.com/magic/tcg/productarticle.aspx?x=mtg/tcg/elvesvsgoblins/productinfo?

**Comment by davidsoderberg** [comment]
I do a fork and make a few icons :smile:

**Comment by jninnes** [comment]
Thanks! I'll try to update the SVGs for ajani and venser in the next couple of days.

**Comment by davidsoderberg** [comment]
Nice If you do that I will continue edit the less file :smile:

**Comment by davidsoderberg** [comment]
Nice now it only 11 icons left, keep up the good work :smile:

**Comment by jninnes** [comment]
Ready to add to less: 
book insert
commander's arsenal
FTV:realms

**Comment by davidsoderberg** [comment]
Sorry I don´t know how to do it when it is three parts :disappointed:

**Comment by jninnes** [comment]
Should be updated into 2 paths now for those three:
https://github.com/jninnes/mtgicons/blob/master/src/icomoon/style.css

**Comment by davidsoderberg** [comment]
Ah nice, I will do those soon :smile:

**Comment by davidsoderberg** [comment]
You got an pull request for those three now.

**Comment by davidsoderberg** [comment]
Anything I can do @jninnes?

**Comment by jninnes** [comment]
Once I've got the other SVGs update I'll let you know. :+1:

**Comment by davidsoderberg** [comment]
:+1:

**Comment by bra1n** [comment]
What about Conspiracy and Commander 2014? =)

**Comment by jninnes** [comment]
There's a few icons that need drawing/redrawing, I'll add them to the list, this is what I've got so far:
- icons in todo.css
- modern masters 2
- commander 2014
- conspiracy

**Comment by jninnes** [comment]
Closing this as we've got most of them. The outstanding ones are included in #21
