### ISSUE TITLE
Hybrid mana symbols don't work with truly empty tags

### ISSUE THREAD

**Issue by bra1n** [jninnes/mtgicons#12]
Tested under Chrome / Linux, here's an example: http://codepen.io/anon/pen/qddXJz

The hybrid mana symbols don't render correctly anymore when the container tag is really empty:
- works (somewhat): `<i class='mtg hybrid-rw'>&nbsp;</i>`
- works: `<i class='mtg hybrid-rw'> </i>`
- doesn't work: `<i class='mtg hybrid-rw'></i>`

Anyway, thanks for the great work so far!

**Comment by bra1n** [comment]
I also noticed, that when you use the "space" approach, it will wrap the hybrid mana symbols for shrinking elements, making them look even weirder. (I updated the codepen)
Using `white-space:nowrap` has the negative side-effect that the (hybrid) symbols flow over the container boundaries.

**Comment by jninnes** [comment]
This is fixed in v1.1.4

**Comment by bra1n** [comment]
Wow, that was quick. Thanks! :+1:

**Comment by jninnes** [comment]
No problem. You did most of the work :)
