### ISSUE TITLE
Alpha/Beta/Unlimited/Revised icons are broken

### ISSUE THREAD

**Issue by bra1n** [jninnes/mtgicons#18]
They currently look like this:
``` 
.alpha .path1:before {
  content: "\e600";
  color: rgb(255, 255, 255);
}
.alpha .path2:before {
  content: "\e601";
  margin-left: -1.17578125em;
  color: rgb(0, 0, 0);
}
.alpha .path3:before {
  content: "\e602";
  margin-left: -1.17578125em;
  color: rgb(255, 255, 255);
}
.alpha .path4:before {
  content: "\e603";
  margin-left: -1.17578125em;
  color: rgb(0, 0, 0);
}
.alpha .path5:before {
  content: "\e604";
  margin-left: -1.17578125em;
  color: rgb(255, 255, 255);
}
```
which neither makes sense with the current syntax `<i class="mtg alpha"></i>`, nor does it actually look like anything when you do add `.path` elements into the icon container.

**Comment by davidsoderberg** [comment]
Where did you find this code?

**Comment by bra1n** [comment]
https://github.com/jninnes/mtgicons/blob/master/src/expansions.less#L3

**Comment by jninnes** [comment]
This is the code that's generated from the icomoon app when I compile the SVGs into the fonts. The source SVGs for alpha-revised need to be updated to remove the extra paths.

**Comment by jninnes** [comment]
Fixed in master.
