### ISSUE TITLE
Add further CSS requirements to icons to prevent leaking of styling

### ISSUE THREAD

**Issue by bra1n** [jninnes/mtgicons#19]
I noticed that there aren't any prefixes for the icon classes at the moment, which would cause them to be applied to every element on a page that matches one of the class names. Since they are rather generic sometimes, you should at least have the expansion names prefixed with `.mtg`, and ideally all the other class names too. :-)
I added the `.mtg` prefix to the expansions with my last PR, but it would make sense to also have that for the mana icons and other symbols.
Example: if you have mtgicons loaded and use the class name `tap` somewhere on the website, like `<button class="button tap">A Button!</button>`, it will match and apply the Tap Symbol CSS to the button, which means it will put some (unrenderable) characters before / after the button text.

**Comment by jninnes** [comment]
Done.
