### ISSUE TITLE
correct expansion code

### ISSUE THREAD

**Issue by yshlyakhov** [jninnes/mtgicons#25]
hi,
why didn't use correct expansion code according to wizards naming? I mean json obj below ( please take a look at this http://mtgjson.com/#individualSets)
and when comings vintage masters and zendikar expedition symbols?
in any case NICE work!

{"LEA":"Limited Edition Alpha","LEB":"Limited Edition Beta","ARN":"Arabian Nights","2ED":"Unlimited Edition","CED":"Collector's Edition","CEI":"International Collector's Edition","pDRC":"Dragon Con","ATQ":"Antiquities","3ED":"Revised Edition","LEG":"Legends","DRK":"The Dark","pMEI":"Media Inserts","FEM":"Fallen Empires","pLGM":"Legend Membership","4ED":"Fourth Edition","ICE":"Ice Age","CHR":"Chronicles","HML":"Homelands","ALL":"Alliances","RQS":"Rivals Quick Start Set","pARL":"Arena League","pCEL":"Celebration","MIR":"Mirage","MGB":"Multiverse Gift Box","ITP":"Introductory Two-Player Set","VIS":"Visions","5ED":"Fifth Edition","pPOD":"Portal Demo Game","POR":"Portal","VAN":"Vanguard","WTH":"Weatherlight","pPRE":"Prerelease Events","TMP":"Tempest","STH":"Stronghold","PO2":"Portal Second Age","pJGP":"Judge Gift Program","EXO":"Exodus","UGL":"Unglued","pALP":"Asia Pacific Land Program","USG":"Urza's Saga","ATH":"Anthologies","ULG":"Urza's Legacy","6ED":"Classic Sixth Edition","PTK":"Portal Three Kingdoms","UDS":"Urza's Destiny","S99":"Starter 1999","pGRU":"Guru","pWOR":"Worlds","pWOS":"Wizards of the Coast Online Store","MMQ":"Mercadian Masques","BRB":"Battle Royale Box Set","pSUS":"Super Series","pFNM":"Friday Night Magic","pELP":"European Land Program","NMS":"Nemesis","S00":"Starter 2000","PCY":"Prophecy","BTD":"Beatdown Box Set","INV":"Invasion","PLS":"Planeshift","7ED":"Seventh Edition","pMPR":"Magic Player Rewards","APC":"Apocalypse","ODY":"Odyssey","DKM":"Deckmasters","TOR":"Torment","JUD":"Judgment","ONS":"Onslaught","LGN":"Legions","SCG":"Scourge","pREL":"Release Events","8ED":"Eighth Edition","MRD":"Mirrodin","DST":"Darksteel","5DN":"Fifth Dawn","CHK":"Champions of Kamigawa","UNH":"Unhinged","BOK":"Betrayers of Kamigawa","SOK":"Saviors of Kamigawa","9ED":"Ninth Edition","RAV":"Ravnica: City of Guilds","p2HG":"Two-Headed Giant Tournament","pGTW":"Gateway","GPT":"Guildpact","pCMP":"Champs and States","DIS":"Dissension","CSP":"Coldsnap","CST":"Coldsnap Theme Decks","TSP":"Time Spiral","TSB":"Time Spiral \"Timeshifted\"","pHHO":"Happy Holidays","PLC":"Planar Chaos","pPRO":"Pro Tour","pGPX":"Grand Prix","FUT":"Future Sight","10E":"Tenth Edition","pMGD":"Magic Game Day","MED":"Masters Edition","LRW":"Lorwyn","EVG":"Duel Decks: Elves vs. Goblins","pLPA":"Launch Parties","MOR":"Morningtide","p15A":"15th Anniversary","SHM":"Shadowmoor","pSUM":"Summer of Magic","EVE":"Eventide","DRB":"From the Vault: Dragons","ME2":"Masters Edition II","pWPN":"Wizards Play Network","ALA":"Shards of Alara","DD2":"Duel Decks: Jace vs. Chandra","CON":"Conflux","DDC":"Duel Decks: Divine vs. Demonic","ARB":"Alara Reborn","M10":"Magic 2010","V09":"From the Vault: Exiled","HOP":"Planechase","ME3":"Masters Edition III","ZEN":"Zendikar","DDD":"Duel Decks: Garruk vs. Liliana","H09":"Premium Deck Series: Slivers","WWK":"Worldwake","DDE":"Duel Decks: Phyrexia vs. the Coalition","ROE":"Rise of the Eldrazi","DPA":"Duels of the Planeswalkers","ARC":"Archenemy","M11":"Magic 2011","V10":"From the Vault: Relics","DDF":"Duel Decks: Elspeth vs. Tezzeret","SOM":"Scars of Mirrodin","PD2":"Premium Deck Series: Fire and Lightning","ME4":"Masters Edition IV","MBS":"Mirrodin Besieged","DDG":"Duel Decks: Knights vs. Dragons","NPH":"New Phyrexia","CMD":"Magic: The Gathering-Commander","M12":"Magic 2012","V11":"From the Vault: Legends","DDH":"Duel Decks: Ajani vs. Nicol Bolas","ISD":"Innistrad","PD3":"Premium Deck Series: Graveborn","DKA":"Dark Ascension","DDI":"Duel Decks: Venser vs. Koth","AVR":"Avacyn Restored","PC2":"Planechase 2012 Edition","M13":"Magic 2013","V12":"From the Vault: Realms","DDJ":"Duel Decks: Izzet vs. Golgari","RTR":"Return to Ravnica","CM1":"Commander's Arsenal","GTC":"Gatecrash","DDK":"Duel Decks: Sorin vs. Tibalt","pWCQ":"World Magic Cup Qualifiers","DGM":"Dragon's Maze","MMA":"Modern Masters","M14":"Magic 2014 Core Set","V13":"From the Vault: Twenty","DDL":"Duel Decks: Heroes vs. Monsters","THS":"Theros","C13":"Commander 2013 Edition","BNG":"Born of the Gods","DDM":"Duel Decks: Jace vs. Vraska","JOU":"Journey into Nyx","MD1":"Modern Event Deck 2014","CNS":"Magic: The Gathering—Conspiracy","VMA":"Vintage Masters","M15":"Magic 2015 Core Set","CPK":"Clash Pack","V14":"From the Vault: Annihilation (2014)","DDN":"Duel Decks: Speed vs. Cunning","KTK":"Khans of Tarkir","C14":"Commander 2014","DD3_DVD":"Duel Decks Anthology, Divine vs. Demonic","DD3_EVG":"Duel Decks Anthology, Elves vs. Goblins","DD3_GVL":"Duel Decks Anthology, Garruk vs. Liliana","DD3_JVC":"Duel Decks Anthology, Jace vs. Chandra","FRF_UGIN":"Ugin's Fate promos","FRF":"Fate Reforged","DDO":"Duel Decks: Elspeth vs. Kiora","DTK":"Dragons of Tarkir","TPR":"Tempest Remastered","MM2":"Modern Masters 2015 Edition","ORI":"Magic Origins","V15":"From the Vault: Angels","DDP":"Duel Decks: Zendikar vs. Eldrazi","BFZ":"Battle for Zendikar","EXP":"Zendikar Expedition"}

**Comment by phrozen** [comment]
+1
Using the "official" expansion codes would be super helpful, and just for clarity sake... is the link for that JSON document.

http://mtgjson.com/json/SetList.json

**Comment by jninnes** [comment]
Take a look at v2.0.0! Thanks for the issue report. Let me know if there are any I've missed.

I'll create a new issue for adding Vintage Masters

**Comment by bra1n** [comment]
Hey, small comment concerning the "correct" set codes: the ones you listed are not the official ones used by WotC.
Example:
Starter, in your list, is S99, while on Gatherer, it is P3
http://gatherer.wizards.com/Handlers/Image.ashx?type=symbol&set=S99&size=large
http://gatherer.wizards.com/Handlers/Image.ashx?type=symbol&set=P3&size=large

I don't know where MTGJSON is taking their set codes from, but I'd rather stick to the Gatherer/WotC ones and have the MTGJSON as fallback, rather than having ONLY those from MTGJSON.

**Comment by jninnes** [comment]
http://archive.wizards.com/Magic/magazine/article.aspx?x=mtgcom/askwizards/0804 lists the official set codes for early sets. Seems like gatherer is using another code rather than the official ones. 

I can re-add the 2-letter gatherer set codes as another alternative, as they won't conflict with future sets.

**Comment by jninnes** [comment]
See https://github.com/jninnes/mtgicons/releases/tag/v2.0.1

**Comment by bra1n** [comment]
Awesome, thanks! :)
