### ISSUE TITLE
Loyalty Symbols

### ISSUE THREAD

**Issue by ej52** [jninnes/mtgicons#28]
Hi,

Any chance of getting the loyalty symbols for planeswalkers added?
eg. https://github.com/andrewgioia/Mana 
ms-loyalty-up, .ms-loyalty-down, .ms-loyalty-zero, .ms-loyalty-start

Would prefer to use your font, as it has all the set symbols but I do need the loyalty symbols too :)

Thanks

**Comment by jninnes** [comment]
I'll see what I can do.

**Comment by jninnes** [comment]
I've got a first pass developed and updated to https://rawgit.com/jninnes/mtgicons/develop/demo/demo.html
Still got some testing to do on it.

**Comment by ej52** [comment]
Thanks, they look great :)

**Comment by flyingmutant** [comment]
To be completely honest — they could use some work regarding +/– and number placement. Compare

<img width="88" alt="2015-11-16 16 41 17" src="https://cloud.githubusercontent.com/assets/73059/11183120/037045ca-8c81-11e5-96e5-63e3170cf4fc.png">
<img width="89" alt="2015-11-16 16 41 27" src="https://cloud.githubusercontent.com/assets/73059/11183122/0590aaf2-8c81-11e5-96b4-6ac8f31448d8.png">

with

<img width="47" alt="2015-11-16 16 43 05" src="https://cloud.githubusercontent.com/assets/73059/11183143/29c3e420-8c81-11e5-8342-f537a135cfa0.png">
