### ISSUE TITLE
Add new icons - Commander 2015, Blessed vs Cursed

### ISSUE THREAD

**Issue by jninnes** [jninnes/mtgicons#30]
Add Commander 2015 Icon (http://magic.wizards.com/en/articles/archive/arcana/announcing-magic-gathering-commander-2015-2015-08-05)
Add Duel Decks: Blessed vs Cursed (http://magic.wizards.com/en/articles/archive/feature/announcing-duel-decks-blessed-vs-cursed-2015-11-02)

**Comment by bra1n** [comment]
http://magic.wizards.com/en/articles/archive/arcana/announcing-shadows-over-innistrad-2015-11-02
Shadows over Innistrad has an icon now.

**Comment by jninnes** [comment]
Added in 2.1.0
