### ISSUE TITLE
Hybrid/phyrexian mana should not require special classes

### ISSUE THREAD

**Issue by flyingmutant** [jninnes/mtgicons#31]
It will be much more convenient to use e.g. `.mana-wu` (hybrid) + `.mana-wp` (phyrexian) naming scheme, without special `hybrid-` and `phyrexian-` prefixes (which serve no real purpose). This way,

- overall naming scheme is much simpler
- interoperability with popular `{...}{...}{...}` (used by at least magiccards.info and mtgjson) mana cost syntax is much easier (no need to special-case anything)

So – please consider changing `hybrid-` to `mana-`, and `phyrexian-*` to `mana-*p`.

**Comment by jninnes** [comment]
Good suggestion! I'm still supporting the phyriexian and hybrid prefixes for backwards compatibility, but now the mana- prefix works too.
