### ISSUE TITLE
Rarity overlays for from-the-vault-angels don't work properly

### ISSUE THREAD

**Issue by jorn86** [jninnes/mtgicons#32]
The rarity overlays for from-the-vault-angels only add a colored border, instead of changing the entire icon's color. You can also see this on the demo page. I'm guessing it's a question of which glyph goes on top of the other?

PS. Thanks for providing this awesome library!

**Comment by bra1n** [comment]
I opened a PR that takes care of this issue. :)

**Comment by jninnes** [comment]
Added in 2.1.1
